name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        # Deploy to the gh-pages branch
        target_branch: github-pages
        # VuePress default output directory
        build_dir: docs/.vuepress/dist
      env:
        # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
